[package]
name = "nimiq-account"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Account primitives to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
lazy_static = "1.3"
log = "0.4"
parking_lot = "0.10"
rand = "0.7"

beserial = { path = "../../beserial", version = "0.1" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1" }
nimiq-bls = { path = "../../bls", version = "0.1" }
nimiq-hash = { path = "../../hash", version = "0.1" }
nimiq-keys = { path = "../../keys", version = "0.1" }
nimiq-primitives = { path = "..", version = "0.1", features = ["coin", "policy", "validators"] }
nimiq-transaction = { path = "../transaction", version = "0.1" }
nimiq-utils = { path = "../../utils", version = "0.1", features = ["hash-rng"] }
nimiq-vrf = { path = "../../vrf", version = "0.1" }

[dev-dependencies]
hex = "0.4"
