[package]
name = "nimiq-handel"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
futures = { version = "0.3", features = ["thread-pool"] }
lazy_static = "1.3"
log = "0.4"
parking_lot = "0.10"
rand = "0.7"
stopwatch = "0.0"
tokio = { version = "0.2", features = ["time"] }

beserial = { path = "../beserial", version = "0.1" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
nimiq-bls = { path = "../bls", version = "0.1" }
nimiq-collections = { path = "../collections", version = "0.1", features = ["bitset"] }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["math", "mutable-once", "observer", "timers"] }

[dev-dependencies]
hex = "0.4"
