[package]
name = "nimiq-metrics-server"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "Prometheus metrics server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
base64 = "0.10"
failure = "0.1"
futures = "0.3"
hyper = "0.13"
log = "0.4"
native-tls = "0.2"
tokio = { version = "0.2", features = ["tcp"] }
tokio-tls = "0.3"

beserial = { path = "../beserial", version = "0.1" }
nimiq-block = { path = "../primitives/block", version = "0.1" }
nimiq-block-albatross = { path = "../primitives/block-albatross", version = "0.1" }
nimiq-blockchain = { path = "../blockchain", version = "0.1", features = ["metrics"] }
nimiq-blockchain-albatross = { path = "../blockchain-albatross", version = "0.1", features = ["metrics"] }
nimiq-blockchain-base = { path = "../blockchain-base", version = "0.1", features = ["metrics"] }
nimiq-consensus = { path = "../consensus", version = "0.1" }
nimiq-mempool = { path = "../mempool", version = "0.1" }
nimiq-network = { path = "../network", version = "0.1", features = ["metrics"] }
