[package]
name = "nimiq-blockchain"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
hex = "0.4"
log = "0.4"
parking_lot = "0.10"

beserial = { path = "../beserial", version = "0.1" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
fixed-unsigned = { path = "../fixed-unsigned", version = "0.1" }
nimiq-account = { path = "../primitives/account", version = "0.1" }
nimiq-accounts = { path = "../accounts", version = "0.1" }
nimiq-block = { path = "../primitives/block", version = "0.1" }
nimiq-blockchain-base = { path = "../blockchain-base", version = "0.1" }
nimiq-database = { path = "../database", version = "0.1", features = ["full-nimiq"] }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-keys = { path = "../keys", version = "0.1" }
nimiq-network-primitives = { path = "../network-primitives", version = "0.1", features = ["networks", "time"] }
nimiq-primitives = { path = "../primitives", version = "0.1" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1" }
nimiq-tree-primitives = { path = "../accounts/tree-primitives", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["observer", "unique-ptr", "iterators"] }

[dev-dependencies]
atomic = "0.4"

[features]
default = ["transaction-store"]
metrics = ["nimiq-blockchain-base/metrics"]
transaction-store = []
